[package]
  cjc-version = "1.0.4"
  name = "cangjieraylib"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "-Woff unused -B /usr/lib/gcc/x86_64-redhat-linux/15/ -Llib/ -lraylib"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
